apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  containers:
  - name: redis
    image: asia.gcr.io/gcp-final-task-348821/redis:1.0
    ports:
    - containerPort: 6379